### ISSUE TITLE
Error when opening the page

### ISSUE THREAD

**Issue by tordans** [chrieke/geojson-validator#7]
https://geojson-validator.streamlit.app/

<img width="751" alt="image" src="https://github.com/chrieke/geojson-validator/assets/111561/744d9550-b48f-41be-aa37-78663b0bfcff">

**Comment by chrieke** [comment]
Oh thanks for reporting this, big oversight! Released fix version 0.5.1 and updated the app, working again:
https://geojson-validator.streamlit.app/
